### ISSUE TITLE
GRISS to flat CSV, matching GBIF and adding acceptedKey

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/alien-species-checklist#39]
Similar to the concatenated and waarnemingen lists, a matching with GBIF is needed to make comparison possible.

**Comment by peterdesmet** [comment]
@timadriaens @SoVDH before we move further: **what is the expected output here**?

In other words: How do we plan to validate the list we got from GRIIS? We now created an aggregated, standardized checklist from the sources we trust: https://github.com/inbo/alien-species-checklist/blob/30801e9a03145378626ec27962da36b1b2ed4e74/data/processed/aggregated-checklist.tsv Do we give them that list or should we crossref ours with GRIIS (= more work)?

**Comment by peterdesmet** [comment]
Closing issue, project is archived. If issue is still relevant, submit to the actively maintained [TrIAS unified checklist](https://github.com/trias-project/unified-checklist).
