### ISSUE TITLE
Correct typos in data (i.e. fuzzy matches)

### ISSUE THREAD

**Issue by DimEvil** [inbo/alien-species-checklist#41]
* [x] Select in concatenated.tsv file for the fuzzy matches
* [x] Compare the original scientificName with the scientificName_gbif
* [x] double check the names (eol.org , google...)
* [x] Correct typos!

(17 fuzzy matches)

**Comment by peterdesmet** [comment]
I have to update the fuzzy match file, based on the new backbone taxonomy

**Comment by peterdesmet** [comment]
Who will take on this task? The file has been updated.

**Comment by DimEvil** [comment]
I ll give it a try :)

**Comment by DimEvil** [comment]
The corrected fuzzy match should be reintegrated in the concatenated.tsv

**Comment by peterdesmet** [comment]
Imported in concatenated at ca04720e576b71fb0ba41e8e881d902a7a533ec7. The fuzzy match list was removed in 6b5b3fb361d04fe77d911fc249d56822a80a5d2f, but can still be accessed at https://github.com/inbo/alien-species-checklist/blob/d6911b04e1c0ab8c3609e1148438c8167fee6047/data/fuzzy-matches.tsv
