### ISSUE TITLE
Create value choice menus for each term in register

### ISSUE THREAD

**Issue by timadriaens** [inbo/alien-species-checklist#58]
we need to provide all potential values for the terms in light of future updates, and describe those here

**Comment by timadriaens** [comment]
Habitats: 

marine
estuarine
terrestrial 
freshwater

+ combinations
 e.g. marine | estuarine, marine | terrestrial, marine | freshwater, marine | estuarine | freshwater | terrestrial etc. etc.

hope you guys can assist in doing this in a non-manual fashion...

**Comment by stijnvanhoey** [comment]
@timadriaens, I'm assuming that the sequence is not important, so marine | estuarine is the same as estuarine | marine?

**Comment by peterdesmet** [comment]
Where would these values lists be used?

I would argue we need to normalize the data first (e.g. splitting habitat information in several rows). This is also done in a Darwin Core Archive. We can then just use the controlled vocabulary, rather than providing every permutation of combinations.

**Comment by peterdesmet** [comment]
Just for reference: this has been done by @stijnvanhoey at https://github.com/inbo/alien-species-checklist/commit/4c0c1034a0b5dc6e1e283b5020cb4609b98df827
