### ISSUE TITLE
Complete metadata for macroinvertebrates checklist

### ISSUE THREAD

**Issue by DimEvil** [inbo/alien-species-checklist#60]
Complete the metadata section in the ipt: http://oefendata.inbo.be/ipt/manage/resource.do?r=alien-macroinvertebrates-checklist

A good start is this article (in press) http://www.aquaticinvasions.net/2016/ACCEPTED/AI_2016_Boets_etal_correctedproof.pdf
or the metadata from the occurrence file: http://data.inbo.be/ipt/resource?r=alien-macroinvertebrate-occurrences

**Comment by peterdesmet** [comment]
@OscarDore / @DimEvil what are the plans for the publication of this checklist? Who will pick this up?

**Comment by peterdesmet** [comment]
This checklist has been published as part of TrIAS: https://doi.org/10.15468/yxcq07
