### ISSUE TITLE
create alien macroinvertebrates checklist IPT repository 

### ISSUE THREAD

**Issue by DimEvil** [inbo/alien-species-checklist#61]

**Comment by DimEvil** [comment]
http://oefendata.inbo.be/ipt/manage/resource.do?r=alien-macroinvertebrates-checklist

**Comment by peterdesmet** [comment]
The name of the occurrence dataset is (sadly?): `alien-macroinvertebrate-occurrences` (no plural), the website uses `https://github.com/inbo/alien-macroinvertebrates` (plural). I also prefer plural.

Is it an option to update the occurrence dataset shortname? Is it referenced in Boets et al.?

**Comment by DimEvil** [comment]
*in the article -->* The occurrence dataset is available at: http://data.inbo.be/ipt/resource?r=alien-macroinvertebrate-occurrences and on GBIF: http://doi.org/10.15468/xjtfoo.  

I would not try to ask the editor to change the manuscript again... but I could change to http://oefendata.inbo.be/ipt/manage/resource?r=alien-macroinvertebrate-checklist if you prefer. (but i'm not really in favour of this, we can always change to what we want if we move to production)

**Comment by peterdesmet** [comment]
No, let's keep it plural.
