### ISSUE TITLE
standardization of terms

### ISSUE THREAD

**Issue by timadriaens** [inbo/alien-species-checklist#62]
we finished standardization of fields invasionStage, introductionPathway, habitat, nativeRange and presence https://docs.google.com/spreadsheets/d/1KJX6QBhv2xmDffYtXGt6FHV41Pm_eQjcUrDqxZxouvQ/edit#gid=0

**Comment by timadriaens** [comment]
Some explanations of our way of working/assumptions/choices we made:

| = AND The recommended best practice is to separate the values with a vertical bar (' | '). 
A | B    =    B | A 
we use | because it’s the common value denominator in dwca

to be determined by experts = preferably to be complemented and adjusted in the source dataset

**Comment by timadriaens** [comment]
**habitat **

marine
estuarine
terrestrial 
freshwater
combinations

if macroinverts = brackish, we assumed they are estuarine (--> based on sampling protocols described in boets et al)

**Comment by peterdesmet** [comment]
I have copied the mapping from Google Spreadsheet to this repo: https://github.com/inbo/alien-species-checklist/tree/master/mapping. I made the values lowercase and made sure `B | A` was changed to `A | B`. Please no longer update the spreadsheet!

I still have to:

* [ ] add presence (as that seems more complicated)
* [ ] do the AB=BA check for introductionPathway

**Comment by peterdesmet** [comment]
All vocabs and mappings have been added to https://github.com/inbo/alien-species-checklist/tree/master/vocabularies

Regarding indicating "Flanders" for estuarine species in WRIMS:

1. The habitat info is not listed in WRIMS, so we have to rely on outside information: what do we choose then?
2. The species could be listed in the other datasets
3. We don't populate coast, BEEZ or BPNS either for marine species potentially not listed in WRIMS.

So, I would leave this as is and keep it to what we have in the sources.
