### ISSUE TITLE
Merge controlled values in concatenated data

### ISSUE THREAD

**Issue by peterdesmet** [inbo/alien-species-checklist#64]
@stijnvanhoey can you create a script to merge the controlled values in the concatenated data?

* The controlled data should be added in existing empty columns, with the same name as the controlled vocabulary (e.g. `invasionStage`)
* The mapping should be done on `dataset`= `datasetName`, `verbatimValue` = e.g `verbatimInvasionStage`
* It would be nice to get errors if a mapping cannot be found for non-blank values...

The mappings to use are:

* [invasionStage](https://github.com/inbo/alien-species-checklist/blob/master/vocabularies/invasionStage-mapping.tsv)
* [introductionPathway](https://github.com/inbo/alien-species-checklist/blob/master/vocabularies/introductionPathway-mapping.tsv)
* [habitat](https://github.com/inbo/alien-species-checklist/blob/master/vocabularies/habitat-mapping.tsv)
* [nativeRange](https://github.com/inbo/alien-species-checklist/blob/master/vocabularies/nativeRange-mapping.tsv)
* [presence](https://github.com/inbo/alien-species-checklist/blob/master/vocabularies/presence-mapping.tsv): note, these are 7 columns that need to be mapped together.

**Comment by stijnvanhoey** [comment]
All mappings were done and concatenated file updated. All non-blank values could be translated, so great job @timadriaens @SoVDH!

Please @peterdesmet check https://github.com/inbo/alien-species-checklist/blob/master/data/concatenated.tsv before closing this issue

**Comment by peterdesmet** [comment]
Checked.
