### ISSUE TITLE
Invasive Pathways and InvasiveDistribution DwC extensions in sandbox + vocabulary on Pathways

### ISSUE THREAD

**Issue by DimEvil** [inbo/alien-species-checklist#65]
http://oefendata.inbo.be/ipt/admin/vocabulary.do?id=http://rs.gbif.org/vocabulary/issg/invasiveness
&
http://oefendata.inbo.be/ipt/admin/extension.do?id=http%3A%2F%2Frs.gbif.org%2Fissg%2Fterms%2FDistribution

Added some sandbox extensions on the 'oefenIPT'. Not sure if these were already noticed.
Can we use this in one way or another?

**Comment by DimEvil** [comment]
Also this is a rather new extension:

http://oefendata.inbo.be/ipt/admin/extension.do?id=http%3A%2F%2Frs.gbif.org%2Fissg%2Fterms%2FPathways

**Comment by peterdesmet** [comment]
Public versions:

* http://rs.gbif.org/sandbox/vocabulary/issg/
* http://rs.gbif.org/sandbox/extension/issg-distribution.xml
* http://rs.gbif.org/sandbox/extension/issg-pathway.xml

**Comment by peterdesmet** [comment]
This is standard related and I assume all of this will be discussed at the IAS session at TDWG, so I'm closing the issue here.
