### ISSUE TITLE
Invasive species not in concatenated

### ISSUE THREAD

**Issue by peterdesmet** [inbo/alien-species-checklist#66]
_Update: for the missing species, see this file: https://github.com/inbo/alien-species-checklist/blob/master/notebooks/2-peterdesmet-merge-aggregated-checklist-with-shortlist.ipynb_

From the 152 species on [our shortlist](https://github.com/inbo/invasive-t0-occurrences/blob/master/species-list/species-list.tsv), 138 species were found in the concatenated file (using the `GBIF acceptedKey`). Hooray! 14 species however are not: some are just not in the `concatenated`, the others had no GBIF match: we should try to solve these.

| Scientific name | EU concern status | In concatenated? | GBIF match? |
| --- | --- | --- | --- |
| Bison bison | under consideration | - | 2441176 |
| Heracleum persicum | listed | - | 3628745 |
| Herpestes javanicus | listed | - | 2434271 |
| Impatiens edgeworthii |  | - | 4936345 |
| Microstegium vimineum | under consideration | - | 5289808 |
| Pennisetum setaceum | under consideration | - | 2706134 |
| Persicaria perfoliata | listed | - | 4033648 |
| Procambarus fallax f. virginalis | listed | - | - |
| Pueraria montana | listed | - | 2977636 |
| Solanum eleagnifolium | not listed | - | 7299960 |

**Comment by timadriaens** [comment]
Baccharis = 3129663
Parthenium = 3086784

**Comment by timadriaens** [comment]
most of the others have never been observed and therefore do not occur in the concatenated

**Comment by peterdesmet** [comment]
Thanks, have added manual match for Baccharis & Parthenium.

**Comment by peterdesmet** [comment]
Suggestion what GBIF ID I should take for?

* Cotoneaster integrifolius
* Oenothera cruciata

**Comment by timadriaens** [comment]
C. integrifolius = 3026105 - would be a correct match according to some taxonomical insights so take that one (Manual of Alien Plants: "Lingdi & Brach (2003) ... subsume Cotoneaster integrifolius under C. microphyllus (as var. thymifolius (Baker) Koehne) (see also Klotz 1957).")

**Comment by timadriaens** [comment]
O. cruciata could be 3188886

**Comment by peterdesmet** [comment]
> O. cruciata could be 3188886

http://www.gbif.org/species/3188886 is a variety `Oenothera cruciata var. stenopetala (E.P.Bicknell) Fernald` and synonym of `Oenothera oakesiana (A. Gray) S. Watson`. Do we really want to take that one?

**Comment by peterdesmet** [comment]
These might be better options:

* http://www.gbif.org/species/3188836: synonym of `Camissonia contorta (Dougl.) Kearney`
* http://www.gbif.org/species/7926755: synonym of `Fuchsia parviflora Lindl.`

It is true however that `Oenothera cruciata var. stenopetala (E.P.Bicknell)` is the only one that is a synonym of another `Oenothera`.

**Comment by peterdesmet** [comment]
I've removed names from the shortlist that are now ok in the August GBIF backbone:

```
Baccharis halimifolia
Cotoneaster integrifolius
Oenothera cruciata
Parthenium hysterophorus
```

But we should test again if no new missing names popped up.

**Comment by peterdesmet** [comment]
Todo:

* [ ] Resolve newly missing names (#68): e.g. should bring `Alopochen` back.
* [ ] Decide on RINSE (#69): note that removing it will likely increase the number of shortlist names not in our checklist.
* [ ] Map shortlist to checklist (using `cell.cross`)
* [ ] Document in this issue.
* [ ] See which species we know are in Belgium are missing.

**Comment by timadriaens** [comment]
Solanum eleagnifolium does occur in Plants, but spelled as Solanum el**aea**gnifolium Cav.

**Comment by peterdesmet** [comment]
The missing species can now be generated by a notebook: https://github.com/inbo/alien-species-checklist/blob/master/notebooks/2-peterdesmet-merge-aggregated-checklist-with-shortlist.ipynb

**Comment by peterdesmet** [comment]
@timadriaens, as discussed: verify if no important names are omitted from the aggregated list. An alternative is to use the shortlist as another source for the concatenated list... not sure if that will complicate things.

**Comment by peterdesmet** [comment]
Closing issue, project is archived. If issue is still relevant, submit to the actively maintained [TrIAS unified checklist](https://github.com/trias-project/unified-checklist).
