### ISSUE TITLE
Create chart for pathway counts

### ISSUE THREAD

**Issue by peterdesmet** [inbo/alien-species-checklist#67]
1. From `concatenated.tsv`
2. Add `speciesKey` for `acceptedKey` (use GBIF services)
3. Group # of unique `speciesKey` by pathway (note: currently ' | ' separated)
4. Order pathways in main and sub categories [according to CBD](https://github.com/inbo/alien-species-checklist/issues/62#issuecomment-217879029)
5. Create bar chart for number of species.

**Comment by peterdesmet** [comment]
You can create this as a public gist.

**Comment by timadriaens** [comment]
Some more specifics on what we need exactly:

Arial 11
Lines 1.5 (no lines around bar charts)
Colors: use following rgb values

![image](https://cloud.githubusercontent.com/assets/16116743/16200461/b67fe7ec-370d-11e6-9706-c43a130af86c.png)

**Comment by stijnvanhoey** [comment]
Tim, los van de styling die ik nog zal uitvoeren, zijn dit e figuren die je wil:

Telling per categorie:
![category_count](https://cloud.githubusercontent.com/assets/754862/16235926/cb16625c-37d6-11e6-97e5-6abe19af9ba4.png)

Telling per subcategorie:
![subcategory_count](https://cloud.githubusercontent.com/assets/754862/16236037/2a6a994e-37d7-11e6-8a55-94f829d38856.png)

Of wil je die op 1 figuur, met telkens de subcategorie in verschillende kleuren voor iedere categorie?

**Comment by timadriaens** [comment]
Something like this:

![figuur2](https://cloud.githubusercontent.com/assets/16116743/16239047/7382fa66-37e3-11e6-8b7b-7856144f3dae.jpeg)

**Comment by timadriaens** [comment]
or if you share the flat table with the dat, i'll do it in r and share the script

**Comment by stijnvanhoey** [comment]
Sounds like a good idea keeping away redundant work (and I'm a fan of ggplot); file is here: https://github.com/inbo/alien-species-checklist/blob/master/utilities/viz_pathways/fig_base.tsv

Great if you would share the R-script, I'll integrate it in the notebook when available

**Comment by peterdesmet** [comment]
Are there still plans to integrate this or can we close this issue?

**Comment by stijnvanhoey** [comment]
@timadriaens I do not know if you have the R-code still available, but in case you still want to apply the code and create the figure, the output will be moved to the https://github.com/inbo/alien-species-checklist/tree/master/data/interim folder when the structure-branch is merged. Feel free to ask assistance with the R-code

**Comment by timadriaens** [comment]
@stijnvanhoey here's the r script we used to create the graph
[grafiek_pathways.zip](https://github.com/inbo/alien-species-checklist/files/442066/grafiek_pathways.zip)

**Comment by stijnvanhoey** [comment]
I adjusted the code, resulting in the following graph:

![pathway_graph](https://cloud.githubusercontent.com/assets/754862/18056839/db82eecc-6e0d-11e6-8e9a-e7d62cf009c6.png)
The code is added to the repo: https://github.com/inbo/alien-species-checklist/blob/structure/src/grafiek_pathways/grafiek_pathways.R

**Comment by timadriaens** [comment]
can you order the subcategories (x-axis) from high to low number of species within headline categories (release, escape...)?

**Comment by stijnvanhoey** [comment]
Good comment. Furthermore, I will adapt the graph in order to facilitate the reading of the x-axis by turning it 90 degrees. At the same time, the facet-headers can be rotated as well, making them well-readable too.

**Comment by stijnvanhoey** [comment]
Something like this?
![pathway_graph](https://cloud.githubusercontent.com/assets/754862/18088618/de531f60-6ebb-11e6-
95e5-88b0a1e5df80.png)

**Comment by stijnvanhoey** [comment]
The cumulative numbere of species in function of time, split by habitat is currently formatted as follows:
![cumulatief_aantal_invasieve](https://cloud.githubusercontent.com/assets/754862/18329320/2abcf342-7553-11e6-8631-f124ac75fa35.png)

As the combination of cumsum and factor split up resulted in wrong counts (basically double as the next level starts counting at the max of the previous), a workaround was implemented. However, this will probably need alteration in the future.

**Comment by peterdesmet** [comment]
Closing issue, project is archived. If issue is still relevant, submit to the actively maintained [TrIAS indicators](https://github.com/trias-project/indicators)
