### ISSUE TITLE
Can we consider RINSE out of scope?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/alien-species-checklist#69]
`rinse` and `rinse-annex-b` (together "RINSE") comprise 6,706 names or 70% of the 9,552 names in our concatenated file. In other words, it's biggest slice, but **I'm starting to wonder if it actually adds much useful information to our checklist?** Some stats (based on the [gbif august backbone processed file](https://github.com/inbo/alien-species-checklist/blob/master/data/concatenated-uat.tsv)):

## Invasive species information

The **only** invasive species information RINSE provides is **habitat**:

dataset | habitat | introductionPathway | invasionStage | nativeRange | firstObservation | introductionMode | invasiveness
--- | --- | --- | --- | --- | --- | --- | ---
fishes | 100% | 100% | 100% | > 95% | 100% | 0% | 0%
harmonia | 100% | 100% | 75% | 100% | 83% | 0% | 0%
macroinvertebrates | 100% | 100% | 100% | 96% | 100% | 0% | 0%
plants | 0% | 100% | 93% | 91% | 98% | 100% | 0%
**rinse** | **100%** | **0%** | **0%** | **0%** | **0%** | **0%** | **0%**
wrims | 0% (marine) | 0% | 61% | 0% | 53% | 0% | 2%

*Note: I consider `unknown`, `blank` and `to be determined by experts` as no data.*

## Presence/absence information

Less than half of the records in RINSE have definite presence/absence information.

dataset | BE | FL | WA | BR
--- | --- | --- | --- | ---
fishes | 100% | 100% | 0% | 0%
harmonia | 100% | 94% | 94% | 78%
macroinvertebrates | 100% | 100% | 0% | 0%
plants | 99% | 99% | 99% | 99%
**rinse** | **42%** | **0.18%** | **0%** | **0%**
wrims | 100% | 0% | 0% | 0%

*Note: I consider `unknown`, `blank` and `to be determined by experts` as no data. `absent` is considered data.*

## Unique names

Some names are shared between datasets, but to avoid counting different spellings as different names, we map each name with GBIF. That works for 95% of all names (9,120 names). In the numbers below, I'm considering synonyms and accepted names as different unique names (as there are still synonym issues with the names). In total we get 7,120 unique names.

What we see is that RINSE provides 4,536 + 66/2 =  4,569 names that **do not occur in the other datasets**. That 64% of the total unique names, but as shown above, with little added value, except that the name might be one of an invasive species.

dataset | Unique names | Duplicate names within dataset | Names shared with other datasets | No GBIF match
--- | --- | --- | --- | ---
fishes | 1 |  | 22 | 
harmonia | 11 |  | 124 | 5
macroinvertebrates | 4 |  | 63 | 6
plants | 774 |  | 1560 | 76
rinse | 4536 | 66 | 1759 | 345
wrims | 6 | 6 | 188 | 

## How to move forward?

Because RINSE a) does not add a lot of invasive species information, b) mostly comprises information that needs to be determined by experts and c) is the largest chuck of the concatenated file, and thus a burden on processing and verification, I would suggest to remove it from our aggregated checklist. We'll still keep the data of course, but to be able to proceed quicker to a more or less usable checklist of alien species of Belgium (and one we trust more as well), I would consider RINSE out of scope.

Processing the remaining 2,846 names with lots of useful information attached seems like a much more achievable goal at this time, especially since it is a dead-end, non-repeatable process. We can always tackle RINSE when we have the time and resources for it.

@SoVDH @timadriaens what do you think?

**Comment by peterdesmet** [comment]
Forgot about invasionStage, which is now also added to the table above and is *also* 0% populated for RINSE.

**Comment by timadriaens** [comment]
Indeed, it seems the source dataset does not contain any useful information, just the names (I find this problematic for a "published" source, it probably means the list got published in the Neobiota journal without anyone actually checking the quality of the dataset itself). We ought to not spend any time on it for now and wait for the full list (publication in preparation, we could probably get hold of the data through Belinda Gallardo or Hugo Verreycken after they published that paper).

Furthermore, RINSE is in itself a concatenated list from various sources (Harmonia, wnm.be etc.) and it has been checked (e.g. by me and some colleagues) only for some taxonomic groups (mammals, birds, herptiles, fish) and some regions. But this process has not been documented.

**Comment by peterdesmet** [comment]
Thanks, #72 has been merged. Closing this issue.
