### ISSUE TITLE
Clean up utilities

### ISSUE THREAD

**Issue by peterdesmet** [inbo/alien-species-checklist#77]
As mentioned in https://github.com/inbo/alien-species-checklist/pull/71, we should clean up [/utilities](https://github.com/inbo/alien-species-checklist/tree/master/src/utilities)

Decisions:

* `combination_maker`: keep in utilities, but rename to something like `combine_vocabulary_values` + remove `habitats.txt` output. Discussed in #58 
* `concatenation`: is a notebook to explain `csvcat`. The way to call csvcat is mentioned in the README, so I think we can remove this directory
* `merge_controlled_vocabularies`: move and rename to `notebooks/1-stijnvanhoey-map_vocabularies.ipyth` and maybe document a bit further. Note that the vocabularies + their mapping is now at https://github.com/inbo/alien-species-checklist/tree/rinse-out-of-scope/data/vocabularies
* `viz_pathways`: move and rename to `notebooks/0-stijnvanhoey-viz-pathways.ipyth`. I would remove the output images + files if possible.

**Comment by stijnvanhoey** [comment]
The notebooks moved, but their source data files are changed, both in location as structure. I'm keeping this open in order to adapt these in the implementation itself as well.

**Comment by stijnvanhoey** [comment]
restructuring of the repo finalised, closing
