### ISSUE TITLE
Move shortlist, gbif_name_match, patchfile, verified synonyms to this repo

### ISSUE THREAD

**Issue by peterdesmet** [inbo/alien-species-checklist#78]
I would group all species list related files and utilities to this open repository. That means:

* **The shortlist of 150 species used for t0**: we already want to know if all species on the shortlist are in the aggregated: #66. Maybe we could even include it as a separate source for the aggregated list?
* **The gbif_name_match utility**: which is really important for the species list, but also all other files (e.g. t0 or waarnemingen.be). Would be good to have it open.
* **A verified synonym list**: which I started at https://github.com/inbo/alien-species-checklist/blob/master/data/vocabularies/verified-synonyms.tsv and could be combined with the patch file as a check right after name matching with GBIF.

@stijnvanhoey what do you think?

**Comment by stijnvanhoey** [comment]
I agree on the idea of opening the material.

* Concerning the shortlist for t0: Perfectly fine to integrate it in the workflow of this alien species checklist and move it from the t0 repo to this repo. If it is a source file, I would leave that open to Tim.
* name_utility: check!
* synonym-list + patch file: great idea, it will simplify the workflow for the t0 analysis and it will overcome the potential redundancy of correcting gbif-matches in one or the other repo.

Good to go for me.

**Comment by stijnvanhoey** [comment]
In contrast to my previous comment, I would make another division in the restructuring of the repos:
* functionalities related to general workflows for name matching, synonym verification,... should move to the python-utilities repository, as the functions are useful beyond the scope of the invasive checklist repo (or t0 repo)
* The shortlist for invasive species can move to this repo, as it is specific to the projects concerning invasive species
* Concerning the patch-file and synonym-verification; these are invasive-specific as in the species working with, however the patches/corrections could be useful as well in other projects. For the moment, I opt to keep it in this repo, close to the code related to invasive species, what do you think Peter?

**Comment by peterdesmet** [comment]
Agree: generally, I'd say common utilities in python-utilities. Data these are working with (species list, synonyms) are specific, and thus belong in the specific repo.
