### ISSUE TITLE
Oscar News

### ISSUE THREAD

**Issue by OscarDore** [inbo/alien-species-checklist#83]
Hello Everybody.

I'm sorry, I left almost without saying Good Bye.

Just at the end of my Master, It became a bit tricky for me to stay in Belgium and continue my studies or another internship at INBO as I told to Dimitri.

However, I managed to enrol as PhD student at ULB and managing now to find a scholarship or research fund for it. I'm working with Prof. Olivier J. Hardy from the Evolutionary Biology and Ecology Service (ULB).

We applied to the FRIA scholarship in November; unfortunately, this was not successful. But we keep applying to different projects.

I came back to my country (Benin) to renew my Passport and start my field works. I'll be back to Brussels in Jun or earlier.

It was a great pleasure to work with you and I hope I come back soon and find some time to learn some more things. 

Happy New Year and See you Soon

Oscar.

**Comment by peterdesmet** [comment]
Hi Oscar, happy 2017! Good luck with your endeavors!
