### ISSUE TITLE
Subspecies definition of Trachemys scripta Schoepff, 1792

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/alien-species-checklist#85]
In the current list, `Trachemys scripta Schoepff, 1792` is taken into account, for which it is assumed that all subspecies (e.g. `elegans`) are taken into account as well. However, when [checking GBIF](http://www.gbif.org/species/2443002), the only subspecies that is taken into account, is the [Trachemys scripta subsp. troostii ](http://www.gbif.org/species/6157035), whereas [Trachemys scripta subsp. elegans](http://www.gbif.org/species/6157026) and [Trachemys scripta subsp. scripta](http://www.gbif.org/species/7062200) is not defined as a subspecies of Trachemys scripta Schoepff, 1792.

As a result, when downloading data from GBIF based on this accepted name, the `elagans`  nor `scripta` subspecies are part of the downloaded data set. 

@peterdesmet @timadriaens @SanderDevisscher Should we add [Trachemys scripta subsp. elegans](http://www.gbif.org/species/6157026) (and other subspecies) as a separate entry into the aggregated checklist? Or should we directly aim to request adaptations to the taxonomic definition of GBIF?

**Comment by timadriaens** [comment]
yes we should or we'll have an underestimation of the current baseline distribution reported to EASIN, at least in Flanders.

**Comment by peterdesmet** [comment]
So, if I understand correctly all 3 subspecies should have the same parent Trachemys scripta? I'll submit an issue to GBIF.

**Comment by peterdesmet** [comment]
Issue logged at https://github.com/gbif/checklistbank/issues/24.

Question: are there any native species for the whole genus `Trachemys` in Belgium? Because we could (temporarily) use the **genus** to return occurrences for all Trachemys species and subspecies, including Trachemys scripta subsp. elegans and Trachemys scripta subsp. scripta.

**Comment by timadriaens** [comment]
nope, no native turtles in Belgium

**Comment by peterdesmet** [comment]
Ok, then I propose to search for Trachemys for the time being. @stijnvanhoey can you update this in the aggregated checklist?

**Comment by stijnvanhoey** [comment]
Update is done, both in the alien species checklist (thanks @peterdesmet) and the t0 data set.
